server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  datasource:
    url: jdbc:postgresql://localhost/blogggr
    username: blogggr
    password: blogggr123
hmackey: 7A7CFC99DB9802272D1987E287926AC52642417BF2D68455E180412C22