server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  datasource:
    url: jdbc:postgresql://localhost/blogggr
    username: blogggr
    password: blogggr123