server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost/blogggr
    username: postgres
    password: root